### ISSUE TITLE
Set up SendGrid Email Testing

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/permission-portal#216]
In order to ensure our emails are working across clients, we want to set up SendGrid's [Email Testing](https://sendgrid.com/solutions/email-marketing/email-testing/) and include all of our custom emails.

(If you want to take this on, contact `Isaiah (New Mexico, USA)` in Slack for the SendGrid credentials)

**Comment by jcolla-holla** [comment]
according to Isaiah this is no longer needed
