### ISSUE TITLE
Make pending operation rotating circle centered on the button

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/permission-portal#301]
Sometimes the center of the circle is higher than the center of the button, i.e. the login

**Comment by jcolla-holla** [comment]
Something necessary to resolve this uniformly across the app is to consolidate the many `.button` classes (there are at least two with this same name I've found so far) as they have inconsistent `margin-top` properties that lead to the loading graphic getting dropped in and resizing various other elements.

Unless there are concerns, I'm going to simply use the `Application.scss` file to standardize the styling for all class `.button` usage based on merging what we currently have.

Any concerns w this approach @ibeckermayer @aidan-fitz ?  Not sure how much UI consistency/consolidation planning we've done.

**Comment by aidan-fitz** [comment]
^ See #253
