### ISSUE TITLE
Add email to the email sign in link url

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/permission-portal#304]
Instead of saving the email address in `localStorage` for use by `signInWithEmailLink`, put it in the generated url as a path parameter. That way the email sign in link can work for both password resets and first time user emails.

**Comment by aidan-fitz** [comment]
This isn't recommended by Google:
> Do not pass the user’s email in the redirect URL parameters and re-use it as this may enable session injections. (magic link security concerns)
