### ISSUE TITLE
v4 Manage Members page

### ISSUE THREAD

**Issue by jcolla-holla** [covidwatchorg/permission-portal#320]
See [Figma design](https://www.figma.com/file/UqWSmByDzH8k7i0PA438EP/Covid-Watch---Portal-v4-(dev)?node-id=0%3A1)

**Comment by ibeckermayer** [comment]
Update based on convo with Vic: ignore the Figma for now, just bring it in line with the general v4 changes i.e.

"titles, buttons, input fields, etc. shorter/slimmer... removed interior shadows..."
